from __future__ import annotations

from datetime import date
from typing import Any

PRICING_UPDATED_AT = date(2026, 9, 9).isoformat()

FREE_TIER_BY_PROVIDER: dict[str, dict[str, Any]] = {
    "Local NAS": {
        "available": True,
        "label": "NAS-hosted local inference",
        "description": "Runs on the NAS GPU through a loopback-only llama.cpp server. No API key or external prompt transfer is required.",
        "requires_api_key_for_real_call": False,
        "source_url": "https://github.com/QwenLM/Qwen3",
    },
    "Free Gateway": {
        "available": True,
        "label": "No-key public text generation",
        "description": "Public no-key text endpoint for quick demos. Prompts are sent to a public service and should not contain secrets.",
        "requires_api_key_for_real_call": False,
        "source_url": "https://github.com/pollinations/pollinations/blob/main/APIDOCS.md",
    },
    "Alibaba Cloud": {
        "available": True,
        "label": "Model Studio new-user free quota",
        "description": "New Alibaba Cloud Model Studio users may receive per-model free quota, typically valid for 90 days and region/service-scope dependent.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://help.aliyun.com/en/model-studio/new-free-quota",
    },
    "Mistral AI": {
        "available": True,
        "label": "Mistral free mode",
        "description": "Free mode is intended for evaluation and prototyping with limited API rate limits.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://help.mistral.ai/en/articles/698531-why-am-i-hitting-api-rate-limits-and-how-do-i-increase-them",
    },
    "Cohere": {
        "available": True,
        "label": "Cohere trial key",
        "description": "Trial API key usage is free but limited, commonly used for testing and proofs of concept.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://docs.cohere.com/v2/docs/rate-limits",
    },
    "Groq": {
        "available": True,
        "label": "Groq Free Plan",
        "description": "Groq Free Plan API usage is free up to free-tier rate limits and returns 429 when exceeded.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://console.groq.com/docs/billing-faqs",
    },
    "Cerebras": {
        "available": True,
        "label": "Cerebras Free Trial",
        "description": "Cerebras provides $5 in free credits after account creation.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://www.cerebras.ai/pricing",
    },
}

FREE_TIER_BY_MODEL: dict[str, dict[str, Any]] = {
    "google:gemini-2.5-flash": {
        "available": True,
        "label": "Gemini 2.5 Flash Free Tier",
        "description": "Gemini 2.5 Flash has Free Tier input and output pricing marked free of charge, with rate limits and data-use conditions.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
    "google:gemini-2.5-flash-lite": {
        "available": True,
        "label": "Gemini 2.5 Flash-Lite Free Tier",
        "description": "Gemini 2.5 Flash-Lite has Free Tier input and output pricing marked free of charge, with rate limits and data-use conditions.",
        "requires_api_key_for_real_call": True,
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
}

NO_FREE_TIER: dict[str, Any] = {
    "available": False,
    "label": "No public free quota in this demo",
    "description": "This catalog does not list a general model-level free quota for this provider.",
    "requires_api_key_for_real_call": True,
    "source_url": None,
}

LLM_MODELS: list[dict[str, Any]] = [
    {
        "id": "local:qwen3-4b",
        "provider": "Local NAS",
        "family": "Qwen3 / llama.cpp",
        "name": "Qwen3 4B Q4_K_M",
        "model": "qwen3-4b",
        "execution": "local",
        "currency": "USD",
        "unit": "request",
        "input": 0.00,
        "output": 0.00,
        "context": "4,096 tokens",
        "max_input_tokens": 4096,
        "api_base": "http://127.0.0.1:8080",
        "note": "Local llama.cpp inference with -ngl 99, -c 4096, --parallel 1, and alias qwen3-4b. The API is bound to loopback only.",
        "note_zh_hant": "由 NAS 上的 llama.cpp 執行，參數為 -ngl 99、-c 4096、--parallel 1，模型別名 qwen3-4b；API 僅綁定本機迴環位址。",
        "source_url": "https://github.com/QwenLM/Qwen3",
    },
    {
        "id": "free:openai-fast",
        "provider": "Free Gateway",
        "family": "Pollinations",
        "name": "Free OpenAI Fast",
        "model": "openai-fast",
        "currency": "USD",
        "unit": "request",
        "input": 0.00,
        "output": 0.00,
        "context": "Anonymous tier",
        "note": "No API key required. Current anonymous model is GPT-OSS 20B via openai-fast.",
        "source_url": "https://github.com/pollinations/pollinations/blob/main/APIDOCS.md",
    },
    {
        "id": "openai:gpt-6-astra",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-6 Astra",
        "model": "gpt-6-astra",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 10.00,
        "cached_input": 1.00,
        "cache_write": 12.50,
        "output": 50.00,
        "context": "1.05M",
        "note": "Standard pricing. Very long prompts above 272K input tokens may use higher rates.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-6-astra",
    },
    {
        "id": "openai:gpt-5.6-sol",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-5.6 Sol",
        "model": "gpt-5.6-sol",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 4.00,
        "cached_input": 0.40,
        "output": 20.00,
        "context": "1.05M",
        "note": "Flagship model for complex professional work.",
        "source_url": "https://developers.openai.com/api/docs/models/compare",
    },
    {
        "id": "openai:gpt-5.6-terra",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-5.6 Terra",
        "model": "gpt-5.6-terra",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 2.00,
        "cached_input": 0.20,
        "output": 12.00,
        "context": "1.05M",
        "note": "Balanced intelligence and cost.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
    },
    {
        "id": "openai:gpt-5.6-luna",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-5.6 Luna",
        "model": "gpt-5.6-luna",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.20,
        "cached_input": 0.02,
        "output": 1.20,
        "context": "1.05M",
        "note": "Cost-sensitive and high-volume workloads.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
    },
    {
        "id": "openai:gpt-5",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-5",
        "model": "gpt-5",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 1.25,
        "cached_input": 0.125,
        "output": 10.00,
        "context": "400K",
        "note": "Previous reasoning model for coding and agentic tasks.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5",
    },
    {
        "id": "openai:gpt-5-mini",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-5 Mini",
        "model": "gpt-5-mini",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.25,
        "cached_input": 0.025,
        "output": 2.00,
        "context": "400K",
        "note": "Lower-latency model for well-defined tasks.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5-mini",
    },
    {
        "id": "openai:gpt-4.1",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-4.1",
        "model": "gpt-4.1",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 2.00,
        "cached_input": 0.50,
        "output": 8.00,
        "context": "1M",
        "note": "Strong non-reasoning model for instruction following and tools.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4.1",
    },
    {
        "id": "openai:gpt-4.1-mini",
        "provider": "OpenAI",
        "family": "ChatGPT / GPT",
        "name": "GPT-4.1 Mini",
        "model": "gpt-4.1-mini",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.40,
        "cached_input": 0.10,
        "output": 1.60,
        "context": "1M",
        "note": "Smaller GPT-4.1 option.",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4.1-mini",
    },
    {
        "id": "anthropic:fable-5.1",
        "provider": "Anthropic",
        "family": "Claude",
        "name": "Claude Fable 5.1",
        "model": "claude-fable-5.1",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 10.00,
        "cache_write": 12.50,
        "cached_input": 0.25,
        "output": 50.00,
        "context": "Provider-defined",
        "note": "Prompt caching price shown uses 5-minute TTL.",
        "source_url": "https://claude.com/platform/api",
    },
    {
        "id": "anthropic:opus-5",
        "provider": "Anthropic",
        "family": "Claude",
        "name": "Claude Opus 5",
        "model": "claude-opus-5",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 5.00,
        "cache_write": 6.25,
        "cached_input": 0.50,
        "output": 25.00,
        "context": "Provider-defined",
        "note": "Complex agentic coding and enterprise work.",
        "source_url": "https://claude.com/platform/api",
    },
    {
        "id": "anthropic:sonnet-5",
        "provider": "Anthropic",
        "family": "Claude",
        "name": "Claude Sonnet 5",
        "model": "claude-sonnet-5",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 2.00,
        "cache_write": 2.50,
        "cached_input": 0.20,
        "output": 10.00,
        "context": "Provider-defined",
        "note": "High-performance model for coding and agents.",
        "source_url": "https://claude.com/platform/api",
    },
    {
        "id": "anthropic:haiku-4.5",
        "provider": "Anthropic",
        "family": "Claude",
        "name": "Claude Haiku 4.5",
        "model": "claude-haiku-4.5",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 1.00,
        "cache_write": 1.25,
        "cached_input": 0.10,
        "output": 5.00,
        "context": "Provider-defined",
        "note": "Fastest, cost-effective Claude model.",
        "source_url": "https://claude.com/platform/api",
    },
    {
        "id": "google:gemini-3.1-pro-preview",
        "provider": "Google",
        "family": "Gemini",
        "name": "Gemini 3.1 Pro Preview",
        "model": "gemini-3.1-pro-preview",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 2.00,
        "cached_input": 0.20,
        "output": 12.00,
        "context": "200K+ tiered",
        "note": "Global standard price for <=200K input tokens; >200K uses higher rates.",
        "source_url": "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
    },
    {
        "id": "google:gemini-3.8-flash",
        "provider": "Google",
        "family": "Gemini",
        "name": "Gemini 3.8 Flash",
        "model": "gemini-3.8-flash",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.75,
        "cached_input": 0.075,
        "output": 3.75,
        "context": "Provider-defined",
        "note": "Promotional global standard price through 2026-12-31.",
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
    {
        "id": "google:gemini-2.5-pro",
        "provider": "Google",
        "family": "Gemini",
        "name": "Gemini 2.5 Pro",
        "model": "gemini-2.5-pro",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 1.25,
        "cached_input": 0.125,
        "output": 10.00,
        "context": "200K+ tiered",
        "note": "Standard API price for prompts <=200K tokens.",
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
    {
        "id": "google:gemini-2.5-flash",
        "provider": "Google",
        "family": "Gemini",
        "name": "Gemini 2.5 Flash",
        "model": "gemini-2.5-flash",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.30,
        "cached_input": 0.03,
        "output": 2.50,
        "context": "1M",
        "note": "Text/image/video input. Audio input has a separate rate.",
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
    {
        "id": "google:gemini-2.5-flash-lite",
        "provider": "Google",
        "family": "Gemini",
        "name": "Gemini 2.5 Flash-Lite",
        "model": "gemini-2.5-flash-lite",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.10,
        "cached_input": 0.025,
        "output": 0.40,
        "context": "1M",
        "note": "Free Tier available for eligible projects; paid tier text/image/video input is $0.10 and output is $0.40 per 1M tokens.",
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
    {
        "id": "deepseek:deepseek-chat",
        "provider": "DeepSeek",
        "family": "DeepSeek",
        "name": "DeepSeek Chat",
        "model": "deepseek-chat",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.27,
        "cached_input": 0.07,
        "output": 1.10,
        "context": "64K",
        "note": "Input price uses cache miss; cache hit shown separately.",
        "source_url": "https://api-docs.deepseek.com/quick_start/pricing-details-usd",
    },
    {
        "id": "deepseek:deepseek-reasoner",
        "provider": "DeepSeek",
        "family": "DeepSeek",
        "name": "DeepSeek Reasoner",
        "model": "deepseek-reasoner",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.55,
        "cached_input": 0.14,
        "output": 2.19,
        "context": "64K",
        "note": "Reasoning model with up to 32K CoT tokens.",
        "source_url": "https://api-docs.deepseek.com/quick_start/pricing-details-usd",
    },
    {
        "id": "alibaba:qwen3.5-plus",
        "provider": "Alibaba Cloud",
        "family": "Qwen",
        "name": "Qwen 3.5 Plus",
        "model": "qwen3.5-plus",
        "currency": "CNY",
        "unit": "1M tokens",
        "input": 4.80,
        "cached_input": 0.80,
        "output": 4.80,
        "context": "128K+ tiered",
        "note": "Global price for <=128K tokens. Alibaba table separates cache hit, input, and output columns.",
        "source_url": "https://help.aliyun.com/en/model-studio/model-pricing",
    },
    {
        "id": "alibaba:qwen-plus",
        "provider": "Alibaba Cloud",
        "family": "Qwen",
        "name": "Qwen Plus",
        "model": "qwen-plus",
        "currency": "CNY",
        "unit": "1M tokens",
        "input": 2.00,
        "cached_input": 0.80,
        "output": 8.00,
        "context": "128K+ tiered",
        "note": "Global price for <=128K tokens.",
        "source_url": "https://help.aliyun.com/en/model-studio/model-pricing",
    },
    {
        "id": "alibaba:qwen-turbo",
        "provider": "Alibaba Cloud",
        "family": "Qwen",
        "name": "Qwen Turbo",
        "model": "qwen-turbo",
        "currency": "CNY",
        "unit": "1M tokens",
        "input": 0.30,
        "output": 0.60,
        "context": "Provider-defined",
        "note": "China Beijing table price; region-specific pricing may differ.",
        "source_url": "https://help.aliyun.com/en/model-studio/model-pricing",
    },
    {
        "id": "mistral:mistral-medium-latest",
        "provider": "Mistral AI",
        "family": "Mistral",
        "name": "Mistral Medium 3.5",
        "model": "mistral-medium-latest",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 1.50,
        "cached_input": 0.15,
        "output": 7.50,
        "context": "Provider-defined",
        "note": "Frontier-class multimodal model optimized for agentic and coding use cases.",
        "source_url": "https://mistral.ai/pricing/api/",
    },
    {
        "id": "mistral:mistral-large-latest",
        "provider": "Mistral AI",
        "family": "Mistral",
        "name": "Mistral Large 3",
        "model": "mistral-large-latest",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.50,
        "cached_input": 0.05,
        "output": 1.50,
        "context": "Provider-defined",
        "note": "Open-weight general-purpose multimodal model.",
        "source_url": "https://mistral.ai/pricing/api/",
    },
    {
        "id": "mistral:mistral-small-latest",
        "provider": "Mistral AI",
        "family": "Mistral",
        "name": "Mistral Small 4",
        "model": "mistral-small-latest",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.15,
        "cached_input": 0.015,
        "output": 0.60,
        "context": "Provider-defined",
        "note": "Cost-sensitive multimodal model.",
        "source_url": "https://mistral.ai/pricing/api/",
    },
    {
        "id": "xai:grok-4.6",
        "provider": "xAI",
        "family": "Grok",
        "name": "Grok 4.6",
        "model": "grok-4.6",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 2.00,
        "cached_input": 0.50,
        "output": 6.00,
        "context": "500K",
        "note": "Regional and high-context pricing may differ.",
        "source_url": "https://docs.x.ai/developers/models/grok-4.6",
    },
    {
        "id": "perplexity:sonar",
        "provider": "Perplexity",
        "family": "Sonar",
        "name": "Sonar",
        "model": "sonar",
        "currency": "USD",
        "unit": "1M tokens + request fee",
        "input": 1.00,
        "output": 1.00,
        "context": "128K",
        "note": "Also has request fees by search context: low/medium/high $5/$8/$12 per 1K requests.",
        "source_url": "https://docs.perplexity.ai/docs/getting-started/pricing",
    },
    {
        "id": "perplexity:sonar-pro",
        "provider": "Perplexity",
        "family": "Sonar",
        "name": "Sonar Pro",
        "model": "sonar-pro",
        "currency": "USD",
        "unit": "1M tokens + request fee",
        "input": 3.00,
        "output": 15.00,
        "context": "Provider-defined",
        "note": "Also has request fees by search context: low/medium/high $6/$10/$14 per 1K requests.",
        "source_url": "https://docs.perplexity.ai/docs/getting-started/pricing",
    },
    {
        "id": "cohere:command-r",
        "provider": "Cohere",
        "family": "Command",
        "name": "Command R",
        "model": "command-r-08-2024",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.15,
        "output": 0.60,
        "context": "128K",
        "note": "Cohere recommends Command A for many new use cases, but public token pricing is available for Command R.",
        "source_url": "https://docs.cohere.com/docs/command-r",
    },
    {
        "id": "groq:openai-gpt-oss-120b",
        "provider": "Groq",
        "family": "GroqCloud",
        "name": "GPT OSS 120B",
        "model": "openai/gpt-oss-120b",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.15,
        "output": 0.60,
        "context": "131K",
        "note": "Groq Free Plan requires an API key and is free up to free-tier limits.",
        "source_url": "https://console.groq.com/docs/models",
    },
    {
        "id": "groq:openai-gpt-oss-20b",
        "provider": "Groq",
        "family": "GroqCloud",
        "name": "GPT OSS 20B",
        "model": "openai/gpt-oss-20b",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.075,
        "output": 0.30,
        "context": "131K",
        "note": "Groq Free Plan requires an API key and is free up to free-tier limits.",
        "source_url": "https://console.groq.com/docs/models",
    },
    {
        "id": "cerebras:gpt-oss-120b",
        "provider": "Cerebras",
        "family": "Cerebras Inference",
        "name": "GPT OSS 120B",
        "model": "gpt-oss-120b",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.25,
        "output": 0.69,
        "context": "Provider-defined",
        "note": "Cerebras offers $5 in free credits after account creation; real calls require an API key.",
        "source_url": "https://www.cerebras.ai/pricing",
    },
    {
        "id": "cerebras:qwen-3-235b",
        "provider": "Cerebras",
        "family": "Cerebras Inference",
        "name": "Qwen 3 235B",
        "model": "qwen-3-235b-a22b-instruct-2507",
        "currency": "USD",
        "unit": "1M tokens",
        "input": 0.60,
        "output": 1.20,
        "context": "Provider-defined",
        "note": "Cerebras offers $5 in free credits after account creation; real calls require an API key.",
        "source_url": "https://www.cerebras.ai/pricing",
    },
]


def provider_summary() -> list[dict[str, Any]]:
    models = all_llm_models(ready_only=True)
    providers = sorted({model["provider"] for model in models})
    return [
        {
            "name": provider,
            "model_count": sum(1 for model in models if model["provider"] == provider),
        }
        for provider in providers
    ]


def model_summary() -> list[dict[str, Any]]:
    return [
        {
            "id": model["id"],
            "provider": model["provider"],
            "family": model["family"],
            "name": model["name"],
            "model": model["model"],
            "execution": model.get("execution", "cloud"),
            "currency": model["currency"],
            "free_tier": free_tier_for_model(model),
        }
        for model in all_llm_models(ready_only=True)
    ]


def get_model(model_id: str) -> dict[str, Any] | None:
    model = next((model for model in all_llm_models(ready_only=True) if model["id"] == model_id), None)
    if not model:
        return None

    enriched = dict(model)
    enriched["free_tier"] = free_tier_for_model(model)
    return enriched


def all_llm_models(*, ready_only: bool) -> list[dict[str, Any]]:
    from app.model_registry import custom_catalog_models

    return [*LLM_MODELS, *custom_catalog_models("openai_compatible_llm", ready_only=ready_only)]


def free_tier_for_model(model: dict[str, Any]) -> dict[str, Any]:
    return FREE_TIER_BY_MODEL.get(model["id"], FREE_TIER_BY_PROVIDER.get(model["provider"], NO_FREE_TIER))
